baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "life-lessons.in"
theme = "hugo-coder"
enableEmoji = true
enableRobotsTXT = true

[pagination]
  pagerSize = 15

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Gurpreet Luthra"
  info = ["Technical Product Consultant"]
  description = "Lessons from living in Tech by Gurpreet"
  keywords = "blog,tech,product,engineering"
  avatarURL = "/images/general/gurpreet-tw-circle-bw-small.png"
  dateFormat = "02-Jan-2006"
  since = 2012
  colorScheme = "auto"
  hideColorSchemeToggle = false
  mainSections = ["posts"]
  customCSS = ["css/custom.css"]

[params.goatCounter]
  code = "luthra"

[params.entry]
  toc = true

[[params.social]]
  name = "Posts"
  icon = "fa-solid fa-newspaper fa-2x"
  weight = 1
  url = "/posts/"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  url = "https://github.com/gsluthra"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/gurpreetluthra"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 4
  url = "/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[Permalinks]
  posts = "/:year/:month/:day/:filename"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Posts"
  weight = 1
  url = "posts/"

[[menu.main]]
  name = "Tags"
  weight = 2
  url = "tags/"

[[menu.main]]
  name = "Presentations"
  weight = 3
  url = "page/presentations/"

[[menu.main]]
  name = "About Me"
  weight = 4
  url = "page/about/"

[[menu.main]]
  name = "Blue Craft"
  weight = 5
  url = "page/bluecraft/"
