baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "life-lessons.in"
theme = "hugo-coder"
paginate = 10
enableEmoji = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Gurpreet Luthra"
  info = ["Technical Product Consultant"]
  description = "Lessons from living in Tech by Gurpreet"
  keywords = "blog,tech,product,engineering"
  avatarURL = "/images/general/gp-profile.png"
  dateFormat = "Mon, Jan 2, 2006"
  since = 2012
  colorScheme = "auto"
  hideColorSchemeToggle = false
  mainSections = ["posts"]

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/gsluthra"

[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/_zenx_"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 3
  url = "/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[Permalinks]
  posts = "/:year/:month/:day/:filename"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Blog"
  weight = 1
  url = "posts/"

[[menu.main]]
  name = "Presentations"
  weight = 2
  url = "page/presentations/"

[[menu.main]]
  name = "About Me"
  weight = 3
  url = "page/about/"

[[menu.main]]
  name = "Blue Craft"
  weight = 4
  url = "page/bluecraft/"
