baseurl = "https://life-lessons.in"
languageCode = "en-us"
title = "life-lessons.in"
theme = "ghostwriter"
disqusShortname = "life-lessons-in"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Life-Lessons.in"
    description = "Adventures in Software and Life"
    github = "https://github.com/gsluthra"
    twitter = "https://twitter.com/_zenx_"
    # email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    readingTime =  true
    readingTimeText = "Estimated reading time:"



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "bw"
    tabWidth = 4

[Permalinks]
    post = "/:year/:month/:day/:filename.html"


[privacy.disqus]
disable = false

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = false


[taxonomies]
  tag = "tags"

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Presentations"
url = "/page/presentations/"
weight = 2

[[menu.main]]
name = "About Me"
url = "/page/about/"
weight = 3