baseurl = "/"
languageCode = "en-us"
title = "life-lessons.in"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Life-Lessons.in"
    description = "Adventures in Software and Life"
    github = "https://github.com/XXX"
    twitter = "https://twitter.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
