baseurl = "/"
languageCode = "en-us"
title = "life-lessons.in"
theme = "ghostwriter"


[Params]
    mainSections = ["post"]
    intro = true
    headline = "Life-Lessons.in"
    description = "Adventures in Software and Life"
    github = "https://github.com/XXX"
    twitter = "https://twitter.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"
    readingTime =  true
    readingTimeText = "Estimated reading time:"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "bw"
    tabWidth = 4

[Permalinks]
    post = "/:year/:month/:day/:filename.html"


[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Presentations"
url = "/page/presentations/"
weight = 2

[[menu.main]]
name = "About Me"
url = "/page/about/"
weight = 3